server:
  port: 8083

spring:
  application:
    name: application-service

  datasource:
    url: jdbc:mysql://localhost:3306/application_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

cloudinary:
  cloud-name: dslw5cccl
  api-key: 991127255952272
  api-secret: J1KQRnx8j_VGN0fAht9OkRSn3kc

management:
  endpoints:
    web:
      exposure:
        include: health, info